[package]
name = "minimal-glfw"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
env_logger = "0.7"
glfw = "0.39"
log = "0.4"
pixels = { path = "../.." }
